# Generated by Django 2.0.2 on 2018-12-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exchange_name', models.CharField(max_length=50)),
                ('bid', models.FloatField(default=0)),
                ('ask', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Prices',
                'db_table': 'prices',
            },
        ),
        migrations.CreateModel(
            name='RestCallStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_date', models.DateTimeField()),
                ('path', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=100)),
                ('verb', models.CharField(max_length=100)),
                ('response_code', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Rest Call Status',
                'db_table': 'rest_call_status',
            },
        ),
    ]
