# Generated by Django 2.0.2 on 2018-10-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exchange_name', models.CharField(max_length=50, unique=True)),
                ('bid', models.FloatField(default=0)),
                ('ask', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Prices',
                'db_table': 'prices',
            },
        ),
    ]
