# Generated by Django 2.0.2 on 2018-10-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='exchange_name',
            field=models.CharField(max_length=50),
        ),
    ]
