# Generated by Django 2.0.2 on 2018-11-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestCallStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_date', models.DateTimeField()),
                ('path', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=100)),
                ('verb', models.CharField(max_length=100)),
                ('response_code', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Rest Call Status',
                'db_table': 'rest_call_status',
            },
        ),
    ]
